server:
  servlet:
    context-path: /packer
  port: ${tomcat.port}
  tomcat:
    connection-timeout: 180000

#日志参数
properties:
  logback:
    path: ${logs.path}
spring:
  datasource:
    url: jdbc:mysql://${datasource.ip}:${datasource.port}/${datasource.db-name}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  redis:
#    database: ${redis.database}
#    host: ${redis.host}
#    port: ${redis.port}
#    password: ${redis.password}
#    timeout: 1000
#    lettuce:
#      pool:
#        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 1000 # 连接池中的最大空闲连接
#        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        min-idle: 500 # 连接池中的最小空闲连接
  cache:
    redis:
      time-to-live: -1

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.avalon.sdk.paycenter.model,com.avalon.sdk.usercenter.model
  configuration:
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

upload:
  win:
    path: ${file.win.path}
  unix:
    path: ${file.unix.path}
  url: ${file.url}

# swagger配置
avalon:
  swagger:
    contact:
      name: xiaobin.wang
    enabled: true
    title: 打包工具
    description: API文档
    version: 0.0.1
    base-package: com.avalon.packer

auth:
  projectToken: ${iam.auth.projectToken}
  authHost: ${iam.auth.authHost}


